<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationIcon>logo.ico</ApplicationIcon>
		<UseWPF>true</UseWPF>
	</PropertyGroup>

	<ItemGroup>
		<Resource Include="logo.ico" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\EasySave\Engine.csproj" />
	</ItemGroup>
</Project>
